spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
