spring:
  data:
    redis:
      host: localhost
      port: 6379
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret-key: t6NfprqeGSdUz505m1/37ReKvlIlHGyoVziS/SF6SJwLoKqZDsKxRfnNj0XatQSdokIl2M6FTzI+zbJeihdRxQ==
  expiration-time-access-token : 600
  expiration-time-refresh-token : 3600
